name: terminal_app

dependencies:
  flutter:
    sdk: flutter
  ssh2: ^0.2.5
  path_provider: ^2.0.11
  file_picker: ^5.0.3
  provider: ^6.0.2
  http: ^0.14.0
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true